2025-08-11 14:46:35,734 - INFO - Running strategy for NVDA at 2025-08-11 07:46:35.734564-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 14:46:35,735 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 14:46:35,736 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 385, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 15:10:27,773 - INFO - Running strategy for NVDA at 2025-08-11 08:10:27.773684-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:10:27,774 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:10:27,774 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 50, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 15:14:52,541 - INFO - Running strategy for NVDA at 2025-08-11 08:14:52.541603-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:14:52,542 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:14:52,543 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 50, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 18:16:59,431 - INFO - Running strategy for NVDA at 2025-08-11 11:16:59.431491-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 18:16:59,432 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 18:16:59,433 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 298, in get_historical_and_live_data
    return get_time_based_historical_data(
        ticker, timeframe, logger, db_api_key, dataset, strategy
    )
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 18:17:01,249 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:02:11,843 - INFO - Running strategy for NVDA at 2025-08-11 13:02:11.843846-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:02:11,848 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:02:14,625 - INFO - Resolved symbol: {'result': {'NVDA': [{'d0': '2025-08-06', 'd1': '2025-08-09', 's': '11667'}, {'d0': '2025-08-11', 'd1': '2025-08-12', 's': '11667'}]}, 'symbols': ['NVDA'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': ['NVDA'], 'not_found': [], 'message': 'Partially resolved', 'status': 1}
2025-08-11 20:02:31,644 - INFO - Created 576 5 bars for NVDA
2025-08-11 20:02:32,202 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:05:48,086 - INFO - Running strategy for NVDA at 2025-08-11 13:05:48.086443-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:05:48,087 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:05:48,087 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 342, in get_historical_and_live_data
    if df is not None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-11 20:05:49,153 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:06:11,278 - INFO - Running strategy for NVDA at 2025-08-11 13:06:11.278952-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:06:11,279 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:06:11,279 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 342, in get_historical_and_live_data
    if df is not None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-11 20:06:12,392 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:18:22,165 - INFO - Running strategy for NVDA at 2025-08-11 14:18:22.164982-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:18:25,420 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:17,916 - INFO - Running strategy for NVDA at 2025-08-11 14:20:17.916821-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:19,245 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:19,610 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:34,650 - INFO - Running strategy for NVDA at 2025-08-11 14:20:34.650920-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:34,650 - INFO - Running strategy for NVDA at 2025-08-11 14:20:34.650920-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:37,383 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:37,383 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:38,010 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:38,010 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:03,341 - INFO - Running strategy for NVDA at 2025-08-11 14:21:03.341669-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:05,241 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:30,711 - INFO - Running strategy for NVDA at 2025-08-11 14:21:30.711929-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:32,051 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:21:32,394 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:00,583 - INFO - Running strategy for NVDA at 2025-08-11 14:33:00.583252-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:02,573 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 98, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 87, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:33:03,413 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:33,420 - INFO - Running strategy for NVDA at 2025-08-11 14:33:33.420673-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:36,427 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:25,082 - INFO - Running strategy for NVDA at 2025-08-11 14:34:25.082532-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:34:28,762 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:58,450 - INFO - Running strategy for NVDA at 2025-08-11 14:34:58.450628-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:00,565 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:35:38,190 - INFO - Running strategy for NVDA at 2025-08-11 14:35:38.189989-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:40,154 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:36:04,938 - INFO - Running strategy for NVDA at 2025-08-11 14:36:04.938528-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:36:06,840 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:37:18,277 - INFO - Running strategy for NVDA at 2025-08-11 14:37:18.277243-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:37:21,134 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:23,652 - INFO - Running strategy for NVDA at 2025-08-11 14:38:23.652126-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:26,177 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:44,309 - INFO - Running strategy for NVDA at 2025-08-11 14:38:44.309668-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:47,355 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:39:11,025 - INFO - Running strategy for NVDA at 2025-08-11 14:39:11.025645-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:39:12,916 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:41:42,564 - INFO - Running strategy for NVDA at 2025-08-11 14:41:42.564742-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:41:44,436 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 88, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:41:44,762 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:43:31,652 - INFO - Running strategy for NVDA at 2025-08-11 14:43:31.652936-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:43:33,333 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 89, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:43:33,664 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:45:49,966 - INFO - Running strategy for NVDA at 2025-08-11 14:45:49.966542-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:45:52,558 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:48:07,773 - INFO - Running strategy for NVDA at 2025-08-11 14:48:07.773405-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:48:10,242 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:51:24,927 - INFO - Running strategy for NVDA at 2025-08-11 14:51:24.927578-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:51:26,878 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:53:18,403 - INFO - Running strategy for NVDA at 2025-08-11 14:53:18.403358-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:53:20,785 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:55:16,795 - INFO - Running strategy for NVDA at 2025-08-11 14:55:16.795115-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:55:23,493 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:56:30,184 - INFO - Running strategy for NVDA at 2025-08-11 14:56:30.184659-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:56:32,747 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:22,031 - INFO - Running strategy for NVDA at 2025-08-11 15:01:22.031898-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:24,110 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:44,193 - INFO - Running strategy for NVDA at 2025-08-11 15:01:44.193325-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:46,417 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:02:01,837 - INFO - Running strategy for NVDA at 2025-08-11 15:02:01.837242-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:02:04,707 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:14,457 - INFO - Running strategy for NVDA at 2025-08-11 15:04:14.457469-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:16,962 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:48,919 - INFO - Running strategy for NVDA at 2025-08-11 15:04:48.919722-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:51,570 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:27:17,854 - INFO - Running strategy for NVDA at 2025-08-11 15:27:17.854116-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:27:21,540 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:32:20,877 - INFO - Running strategy for NVDA at 2025-08-11 15:32:20.877642-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:32:22,871 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:36:15,077 - INFO - Running strategy for NVDA at 2025-08-11 15:36:15.077019-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:36:17,361 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:37:53,927 - INFO - Running strategy for NVDA at 2025-08-11 15:37:53.927669-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:37:56,871 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:04:07,304 - INFO - Running strategy for NVDA at 2025-08-11 16:04:07.304733-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:04:10,957 - INFO - Market closed
2025-08-11 23:04:10,958 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:04:42,585 - INFO - Running strategy for NVDA at 2025-08-11 16:04:42.585699-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:09,560 - INFO - Running strategy for NVDA at 2025-08-11 16:05:09.560093-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:15,857 - INFO - Market closed
2025-08-11 23:05:15,857 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:05:56,497 - INFO - Running strategy for NVDA at 2025-08-11 16:05:56.497465-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:06:53,161 - ERROR - Error fetching historical end time for dataset XNAS.ITCH: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-08-11 23:06:53,162 - ERROR - Error in strategy for NVDA: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 42, in get_historical_end_time
    metadata = DATABENTO_CLIENT.metadata.get_dataset_range(dataset=dataset)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\metadata.py", line 254, in get_dataset_range
    response: Response = self._get(
                         ~~~~~~~~~^
        url=self._base_url + ".get_dataset_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        params=params,
        ^^^^^^^^^^^^^^
        basic_auth=True,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 61, in _get
    with requests.get(
         ~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
    ...<3 lines>...
        timeout=(self.TIMEOUT, self.TIMEOUT),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as response:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 120, in get_historical_and_live_data
    def get_historical_and_live_data(ticker, timeframe, logger, strategy):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    end_time = get_historical_end_time(dataset, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 51, in get_historical_end_time
    safe_historical_end = datetime.now(timezone.utc) - timedelta(minutes=10)
                          ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-08-11 23:09:55,895 - INFO - Running strategy for NVDA at 2025-08-11 16:09:55.895830-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:09:58,727 - INFO - Market closed
2025-08-11 23:09:58,728 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:11:14,071 - INFO - Running strategy for NVDA at 2025-08-11 16:11:14.071930-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:11:16,318 - INFO - Market closed
2025-08-11 23:11:16,318 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:14:12,008 - INFO - Running strategy for NVDA at 2025-08-11 16:14:12.008658-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:14:15,713 - INFO - Market closed
2025-08-11 23:14:15,714 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:20:26,402 - INFO - Running strategy for NVDA at 2025-08-11 16:20:26.402263-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:20:28,139 - INFO - Market closed
2025-08-11 23:20:28,139 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:30:48,438 - INFO - Running strategy for NVDA at 2025-08-11 16:30:48.438174-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:30:50,227 - INFO - Market closed
2025-08-11 23:30:50,228 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:58:03,394 - INFO - Running strategy for NVDA at 2025-08-11 16:58:03.393991-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:05,204 - INFO - Market closed
2025-08-11 23:58:05,204 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:58:45,994 - INFO - Running strategy for NVDA at 2025-08-11 16:58:45.994730-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:48,021 - INFO - Market closed
2025-08-11 23:58:48,021 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:26:03,793 - INFO - Running strategy for NVDA at 2025-08-11 18:26:03.793305-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:26:05,977 - INFO - Market closed
2025-08-12 01:26:05,977 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:27:57,342 - INFO - Running strategy for NVDA at 2025-08-11 18:27:57.342638-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:28:00,657 - ERROR - Error in strategy for NVDA: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 134, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 01:28:01,308 - INFO - Market closed
2025-08-12 01:28:01,308 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:28:44,489 - INFO - Running strategy for NVDA at 2025-08-11 18:28:44.489282-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:28:48,435 - ERROR - Error in strategy for NVDA: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 134, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 01:28:49,551 - INFO - Market closed
2025-08-12 01:28:49,551 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:29:46,954 - INFO - Running strategy for NVDA at 2025-08-11 18:29:46.954294-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:29:53,255 - INFO - Market closed
2025-08-12 01:29:53,255 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:35:31,715 - INFO - Running strategy for NVDA at 2025-08-11 18:35:31.715188-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:35:33,900 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 106, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 101, in get_historical_data
    return df
           ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-12 01:35:35,542 - INFO - Market closed
2025-08-12 01:35:35,542 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:36:10,158 - INFO - Running strategy for NVDA at 2025-08-11 18:36:10.158382-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:36:12,086 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 106, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 101, in get_historical_data
    return df
           ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-12 01:36:13,137 - INFO - Market closed
2025-08-12 01:36:13,166 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:44:47,574 - INFO - Running strategy for NVDA at 2025-08-11 18:44:47.574155-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:44:49,110 - ERROR - Error in strategy for NVDA: name 'start_date' is not defined
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 116, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    start=start_date,
          ^^^^^^^^^^
NameError: name 'start_date' is not defined. Did you mean: 'start_time'?
2025-08-12 01:44:49,699 - INFO - Market closed
2025-08-12 01:44:49,699 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 01:46:57,755 - INFO - Running strategy for NVDA at 2025-08-11 18:46:57.755796-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:46:59,053 - ERROR - Error in strategy for NVDA: name 'start_date' is not defined
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 107, in get_historical_data
    start=start_date,
          ^^^^^^^^^^
NameError: name 'start_date' is not defined. Did you mean: 'start_time'?
2025-08-12 01:47:00,235 - INFO - Market closed
2025-08-12 01:47:00,235 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:28:56,935 - INFO - Running strategy for NVDA at 2025-08-11 19:28:56.935788-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:29:01,673 - INFO - Market closed
2025-08-12 02:29:01,673 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:29:35,835 - INFO - Running strategy for NVDA at 2025-08-11 19:29:35.835728-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:29:40,483 - INFO - Market closed
2025-08-12 02:29:40,483 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:34:55,062 - INFO - Running strategy for NVDA at 2025-08-11 19:34:55.062237-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:34:58,458 - INFO - Market closed
2025-08-12 02:34:58,458 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:35:30,470 - INFO - Running strategy for NVDA at 2025-08-11 19:35:30.470933-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:35:31,886 - ERROR - Error in strategy for NVDA: SymbologyHttpAPI.resolve() missing 1 required positional argument: 'start_date'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 123, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 102, in get_historical_data
    res = DATABENTO_CLIENT.symbology.resolve(
        dataset="XNAS.ITCH",
    ...<2 lines>...
        stype_out="instrument_id"
    )
TypeError: SymbologyHttpAPI.resolve() missing 1 required positional argument: 'start_date'
2025-08-12 02:35:32,808 - INFO - Market closed
2025-08-12 02:35:32,808 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:35:50,513 - INFO - Running strategy for NVDA at 2025-08-11 19:35:50.513209-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:35:51,808 - ERROR - Error in strategy for NVDA: SymbologyHttpAPI.resolve() missing 1 required positional argument: 'start_date'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 123, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 102, in get_historical_data
    res = DATABENTO_CLIENT.symbology.resolve(
        dataset="XNAS.ITCH",
    ...<2 lines>...
        stype_out="instrument_id"
    )
TypeError: SymbologyHttpAPI.resolve() missing 1 required positional argument: 'start_date'
2025-08-12 02:35:52,614 - INFO - Market closed
2025-08-12 02:35:52,614 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:37:29,710 - INFO - Running strategy for NVDA at 2025-08-11 19:37:29.710205-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:37:31,115 - ERROR - Error in strategy for NVDA: SymbologyHttpAPI.resolve() missing 1 required positional argument: 'start_date'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 102, in get_historical_data
    res = DATABENTO_CLIENT.symbology.resolve(
        dataset="XNAS.ITCH",
    ...<2 lines>...
        stype_out="instrument_id"
    )
TypeError: SymbologyHttpAPI.resolve() missing 1 required positional argument: 'start_date'
2025-08-12 02:37:32,162 - INFO - Market closed
2025-08-12 02:37:32,162 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:38:13,856 - INFO - Running strategy for NVDA at 2025-08-11 19:38:13.856301-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:38:16,051 - ERROR - Error in strategy for NVDA: 'MetadataHttpAPI' object has no attribute 'get_dataset'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 130, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 102, in get_historical_data
    meta = DATABENTO_CLIENT.metadata.get_dataset("XNAS.ITCH")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetadataHttpAPI' object has no attribute 'get_dataset'. Did you mean: 'list_datasets'?
2025-08-12 02:38:16,410 - INFO - Market closed
2025-08-12 02:38:16,410 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:39:14,293 - INFO - Running strategy for NVDA at 2025-08-11 19:39:14.293872-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:39:16,606 - ERROR - Error in strategy for NVDA: 'MetadataHttpAPI' object has no attribute 'get_dataset'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 131, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 103, in get_historical_data
    meta = DATABENTO_CLIENT.metadata.get_dataset("XNAS.ITCH")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetadataHttpAPI' object has no attribute 'get_dataset'. Did you mean: 'list_datasets'?
2025-08-12 02:39:17,022 - INFO - Market closed
2025-08-12 02:39:17,023 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:40:09,742 - INFO - Running strategy for NVDA at 2025-08-11 19:40:09.742635-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:40:11,811 - ERROR - Error in strategy for NVDA: cannot access local variable 'res' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 140, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 122, in get_historical_data
    instrument_id = res[symbol][0]
                    ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
2025-08-12 02:40:12,259 - INFO - Market closed
2025-08-12 02:40:12,259 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:42:03,447 - INFO - Running strategy for NVDA at 2025-08-11 19:42:03.447416-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:42:07,078 - ERROR - Error in strategy for NVDA: string indices must be integers, not 'str'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 141, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 109, in get_historical_data
    meta = next(d for d in datasets if d["name"] == dataset)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 109, in <genexpr>
    meta = next(d for d in datasets if d["name"] == dataset)
                                       ~^^^^^^^^
TypeError: string indices must be integers, not 'str'
2025-08-12 02:42:07,432 - INFO - Market closed
2025-08-12 02:42:07,432 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:43:08,270 - INFO - Running strategy for NVDA at 2025-08-11 19:43:08.270178-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:43:10,810 - ERROR - Error in strategy for NVDA: cannot access local variable 'res' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 140, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 122, in get_historical_data
    instrument_id = res[symbol][0]
                    ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
2025-08-12 02:43:11,628 - INFO - Market closed
2025-08-12 02:43:11,628 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:45:58,216 - INFO - Running strategy for NVDA at 2025-08-11 19:45:58.216054-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:46:03,873 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 146, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 141, in get_historical_data
    return df
           ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-12 02:46:04,276 - INFO - Market closed
2025-08-12 02:46:04,276 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:49:35,958 - INFO - Running strategy for NVDA at 2025-08-11 19:49:35.958079-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:49:42,988 - ERROR - Error in strategy for NVDA: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 147, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 130, in get_historical_data
    df = DATABENTO_CLIENT.timeseries.get_range(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset="XNAS.ITCH",
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        end="2024-08-01T16:00:00"
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-12 02:49:43,591 - INFO - Market closed
2025-08-12 02:49:43,591 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:51:55,243 - INFO - Running strategy for NVDA at 2025-08-11 19:51:55.243705-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:52:02,644 - ERROR - Error in strategy for NVDA: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 147, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 130, in get_historical_data
    df = DATABENTO_CLIENT.timeseries.get_range(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset="XNAS.ITCH",
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        end="2024-08-01T16:00:00"
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-12 02:52:03,011 - INFO - Market closed
2025-08-12 02:52:03,011 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 02:53:36,014 - INFO - Running strategy for NVDA at 2025-08-11 19:53:36.014190-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 02:53:42,829 - ERROR - Error in strategy for NVDA: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 148, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 131, in get_historical_data
    df = DATABENTO_CLIENT.timeseries.get_range(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset="XNAS.ITCH",
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        end="2024-08-01T16:00:00"
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-12 02:53:43,428 - INFO - Market closed
2025-08-12 02:53:43,428 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:00:37,670 - INFO - Running strategy for NVDA at 2025-08-11 20:00:37.670220-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:00:48,686 - ERROR - Error in strategy for NVDA: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 149, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 132, in get_historical_data
    df = DATABENTO_CLIENT.timeseries.get_range(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset="XNAS.ITCH",
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        end="2024-08-01T16:00:00"
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 symbology_invalid_request
None of the symbols could be resolved
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-12 03:00:49,027 - INFO - Market closed
2025-08-12 03:00:49,027 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:15:12,601 - INFO - Running strategy for NVDA at 2025-08-11 20:15:12.601589-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:15:19,754 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 150, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 141, in get_historical_data
    print("df", df)
                ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-12 03:15:20,192 - INFO - Market closed
2025-08-12 03:15:20,192 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:18:56,315 - INFO - Running strategy for NVDA at 2025-08-11 20:18:56.315753-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:19:09,757 - INFO - Market closed
2025-08-12 03:19:09,757 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:19:46,616 - INFO - Running strategy for NVDA at 2025-08-11 20:19:46.616493-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:20:11,892 - INFO - Market closed
2025-08-12 03:20:11,893 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:20:28,295 - INFO - Running strategy for NVDA at 2025-08-11 20:20:28.295806-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:22:19,170 - INFO - Running strategy for NVDA at 2025-08-11 20:22:19.170197-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:22:26,611 - INFO - Market closed
2025-08-12 03:22:26,611 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:25:31,186 - INFO - Running strategy for NVDA at 2025-08-11 20:25:31.186412-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:25:37,191 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 148, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 143, in get_historical_data
    return df
           ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-12 03:25:38,052 - INFO - Market closed
2025-08-12 03:25:38,052 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:26:17,520 - INFO - Running strategy for NVDA at 2025-08-11 20:26:17.520827-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:27:08,706 - INFO - Market closed
2025-08-12 03:27:08,706 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:55:35,104 - INFO - Running strategy for NVDA at 2025-08-11 20:55:35.104845-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:55:35,105 - ERROR - Error in strategy for NVDA: __new__() got an unexpected keyword argument 'months'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 114, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
                            ~~~~~~~~~^^^^^^^^^^
TypeError: __new__() got an unexpected keyword argument 'months'
2025-08-12 03:55:35,756 - INFO - Market closed
2025-08-12 03:55:35,756 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 04:01:08,549 - INFO - Running strategy for NVDA at 2025-08-11 21:01:08.549404-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 04:01:08,550 - ERROR - Error in strategy for NVDA: __new__() got an unexpected keyword argument 'months'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
                            ~~~~~~~~~^^^^^^^^^^
TypeError: __new__() got an unexpected keyword argument 'months'
2025-08-12 04:01:08,975 - INFO - Market closed
2025-08-12 04:01:08,975 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 09:44:03,451 - INFO - Running strategy for NVDA at 2025-08-12 02:44:03.451030-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 09:44:03,530 - ERROR - Error in strategy for NVDA: __new__() got an unexpected keyword argument 'months'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_and_live_data
    return df
           ^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_data
    print(f"Error in get_tick_based_data: {e}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
                            ~~~~~~~~~^^^^^^^^^^
TypeError: __new__() got an unexpected keyword argument 'months'
2025-08-12 09:44:31,673 - INFO - Running strategy for NVDA at 2025-08-12 02:44:31.673126-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 09:44:31,673 - ERROR - Error in strategy for NVDA: __new__() got an unexpected keyword argument 'months'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 119, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
                            ~~~~~~~~~^^^^^^^^^^
TypeError: __new__() got an unexpected keyword argument 'months'
2025-08-12 09:44:57,602 - INFO - Running strategy for NVDA at 2025-08-12 02:44:57.601989-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 09:44:57,602 - ERROR - Error in strategy for NVDA: __new__() got an unexpected keyword argument 'months'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 120, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
                            ~~~~~~~~~^^^^^^^^^^
TypeError: __new__() got an unexpected keyword argument 'months'
2025-08-12 09:55:53,720 - INFO - Running strategy for NVDA at 2025-08-12 02:55:53.720085-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 09:56:27,147 - INFO - Running strategy for NVDA at 2025-08-12 02:56:27.147788-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 09:58:25,793 - INFO - Running strategy for NVDA at 2025-08-12 02:58:25.793377-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 10:58:17,737 - INFO - Running strategy for NVDA at 2025-08-12 03:58:17.737028-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 11:04:39,697 - INFO - Running strategy for NVDA at 2025-08-12 04:04:39.696996-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 11:06:50,190 - INFO - Running strategy for NVDA at 2025-08-12 04:06:50.190056-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 12:38:40,909 - INFO - Running strategy for NVDA at 2025-08-12 05:38:40.909242-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 12:38:51,393 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_516t.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 123, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_516t.csv'
2025-08-12 12:42:59,762 - INFO - Running strategy for NVDA at 2025-08-12 05:42:59.762204-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 12:43:07,429 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_516t.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 136, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_516t.csv'
2025-08-12 12:44:43,039 - INFO - Running strategy for NVDA at 2025-08-12 05:44:43.039331-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 12:44:50,204 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_516t.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 137, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 129, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_516t.csv'
2025-08-12 12:46:19,650 - INFO - Running strategy for NVDA at 2025-08-12 05:46:19.650215-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 12:48:25,664 - INFO - Running strategy for NVDA at 2025-08-12 05:48:25.664954-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 12:51:54,873 - INFO - Running strategy for NVDA at 2025-08-12 05:51:54.873487-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 13:53:03,346 - INFO - Running strategy for NVDA at 2025-08-12 06:53:03.346565-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 14:13:24,909 - INFO - Running strategy for NVDA at 2025-08-12 07:13:24.909092-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 14:13:29,373 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_30.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 152, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 144, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=True)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_30.csv'
2025-08-12 14:14:26,553 - INFO - Running strategy for NVDA at 2025-08-12 07:14:26.553826-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 14:14:55,609 - INFO - Running strategy for NVDA at 2025-08-12 07:14:55.609252-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 14:15:00,047 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_30.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 152, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 144, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=True)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_30.csv'
2025-08-12 14:17:54,744 - INFO - Running strategy for NVDA at 2025-08-12 07:17:54.744747-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 14:17:59,235 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_30.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 153, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 145, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=True)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_30.csv'
2025-08-12 14:19:30,566 - INFO - Running strategy for NVDA at 2025-08-12 07:19:30.566536-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 14:19:34,965 - ERROR - Error in strategy for NVDA: [Errno 13] Permission denied: 'NVDA_30.csv'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 154, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 146, in get_historical_data
    df.to_csv(f"{symbol}_{timeframe}.csv", index=True)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: 'NVDA_30.csv'
2025-08-12 15:00:53,264 - INFO - Running strategy for NVDA at 2025-08-12 08:00:53.264485-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:01:31,575 - INFO - Running strategy for NVDA at 2025-08-12 08:01:31.575155-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:01:56,816 - INFO - Running strategy for NVDA at 2025-08-12 08:01:56.816748-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:06:48,310 - INFO - Running strategy for NVDA at 2025-08-12 08:06:48.310651-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:08:28,162 - INFO - Running strategy for NVDA at 2025-08-12 08:08:28.162539-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:10:30,905 - INFO - Running strategy for NVDA at 2025-08-12 08:10:30.905333-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:11:55,157 - INFO - Running strategy for NVDA at 2025-08-12 08:11:55.157861-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:12:49,119 - INFO - Running strategy for NVDA at 2025-08-12 08:12:49.119189-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:16:27,295 - INFO - Running strategy for NVDA at 2025-08-12 08:16:27.294991-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:19:25,880 - INFO - Running strategy for NVDA at 2025-08-12 08:19:25.880585-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:21:48,864 - INFO - Running strategy for NVDA at 2025-08-12 08:21:48.864174-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 15:26:48,525 - INFO - Running strategy for NVDA at 2025-08-12 08:26:48.525961-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
